name: co19_ffi
description: co19 tests for Dart FFI library

# This tests isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0